### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by TheRealMrKam** [Doug-Murphy/LethalCompanyMods#1]
Can you add the vanilla values so we can compare with the changes ? please

Also configs would be nice :)

**Comment by Doug-Murphy** [comment]
Thanks for the feedback! I debated on whether or not I should include the vanilla weights in the readme. As I was writing out the updated values, I did start to include them. However, I removed them for a few reasons. I didn't want this readme to be a copy of the game's documentation and I didn't want to have to worry about maintaining it. If the vanilla values change, then I have to update the readme. This also means that I have to constantly monitor the values to see if they change in each update, and frankly I just didn't want that burden. The Balanced Items mod will almost certainly outlive my time playing this game. Lastly, I really didn't think people would care that much. :D My thought was that if someone was using this mod, that's because they already know that the vanilla weight values are really quite dumb and wouldn't care what the weights _used_ to be. Lol.

I will keep your request for config in mind! As I mentioned in the readme, it's definitely something that was thought about at the start of the mod. Adding in scrap values for more balancing would likely require a config value so that way people can tweak how balanced this mod is. If (when?) config comes into play, weights will be included for sure!

**Comment by Doug-Murphy** [comment]
Reopening for tracking of config inclusion.

**Comment by Doug-Murphy** [comment]
@TheRealMrKam I have a beta release available for config file support. Before I release the update to Thunderstore, I'm curious if you would like to playtest this for me and provide feedback? If so, I would appreciate it! If not, that's ok too. :)

**Comment by TheRealMrKam** [comment]
Sure why not :)

**Comment by Doug-Murphy** [comment]
Fantastic! I just wrote instructions on how to do that in #2 if you could go check that out! I'll close this issue and we can track feedback over there. Thanks!
