### ISSUE TITLE
Consider adding support for setting moon scrap multiplier

### ISSUE THREAD

**Issue by James-Mitschke** [Doug-Murphy/LethalCompanyMods#10]
I've tried adjusting the config before the round starts as well as before a new quote and before the server starts and the average value doesn't seem to impact anything. I've tested items on Experimentation and Assurance and found that item values were way below what my min value should be. Even when these items are sold at 100% value.

e.g. RobotToy average value set to 75, in game value on Assurance is 35, min value should be no less than 60. Interestingly this seems to be way below the min value listed on the Fandom wiki for Assurance as well so I'm unsure if there's modifiers that are impacting this? If so it would be awesome if we could get this as a configurable value for each moon as well!

Either way, this mod is really cool so keep up the great work!

**Comment by Doug-Murphy** [comment]
Hey there! Thanks for the feedback. What you're describing sounds to me like expected behavior actually.

The below is taken from the readme file. My assumption about why this behavior is this way is a balancing mechanic in the game where the easier/earlier moons just simply aren't worth as much.

> It's important to note that the game applies different scrap multipliers at various levels, which means the actual in-game values might be higher than these listed averages.

Also keep in mind that there is no retroactive changing of item values. So if you have an item on your ship, then change the value in the config, the value of that item will not change. However, future items that spawn should have the updated value!

I hope this clears it up.

**Comment by Doug-Murphy** [comment]
> Thanks for the update on this, I did just do a local test too with values incredibly high (1000) and can confirm this is definitely working as expected, yay!

So happy to hear it!

> just didn't expect starting moons to be nearly 50% of actual value haha.

Seriously though! Experimentation is 40% value. 😬

> On the note of multipliers though, do you think this could be configurable by this mod in the future?

It's definitely configurable in the game but putting it in this mod could cause some issues with other mods that do that same though (Weather Multipliers comes to mind). However, I suppose this mod could already cause conflicts if there were any other mods that did what this one does. It does feel like it's in the spirit of this mod so I'll consider it!

**Comment by Doug-Murphy** [comment]
@James-Mitschke I did some thinking on this and some looking on Thunderstore for mods that have this functionality. A fair few mods seem to have functionality like this, it's just packaged with other functionality as well. I find that to be kind of annoying because maybe you _only_ want to adjust multipliers. However, the [MeteoMultiplier](https://thunderstore.io/c/lethal-company/p/Fredolx/MeteoMultiplier/) mod has a configurable multiplier for moons without weather (in addition to moons with weather). I think this mod is sufficiently not cluttered up enough to warrant me not making a new mod to handle this functionality.

Thanks for the feedback though! :)
