### ISSUE TITLE
The mod causes the load times to increase drastically depending on moons and scraps.

### ISSUE THREAD

**Issue by NiranV** [Doug-Murphy/LethalCompanyMods#20]
Each scrap piece is another iteration to run through at least 2 times. (weight and price)
Each moon added is another iteration per scrap piece on top of the 2 additional iterations. (moon rarity)
Each iteration writes several lines of logging code which are incredibly slow and cannot be disabled.

Having just a handful of extra moons and a couple extra scrap items inflates the loading times to insane lengths, having a scrap pack like Dafi's scrap emporium will easily push the load times past 5-10 minutes, that's just the loading times into the lobby, every single time you change to a new moon and land, it repeats several more iterations to write and read every single scrap item on that moon which also inflates the generation times to unbearable times. On top of that logging cannot be disabled thus this part cannot be culled for performance, it's also insanely spammy even without any mods. The mod also does not skip unnecessary parts (such as writing scraps and moons it already added) and iterates through the config creation as well as reading it every single time and neither does disabling any parts of the configuration make a difference. Disabling sell values for instance does not skip writing and reading the sell values for all moons and scraps.

It makes playing with the later versions of this mod unbearably slow.

Suggestions:
Make the mod skip parts you disabled.
Allow disabling logging.
Allow disabling hot-loading to eliminate in-lobby loading times between moons.

**Comment by Doug-Murphy** [comment]
Hey there! I agree that the load times aren't ideal. It's one of those things where I took the stance of "I don't think this is that great. But are my expectations too high? Maybe. I need to let the community decide if this is acceptable or not." So really I was just kind of waiting to hear this kind of feedback. I think there are a few things to clarify though!

> Each scrap piece is another iteration to run through at least 2 times. (weight and price)
> Each moon added is another iteration per scrap piece on top of the 2 additional iterations. (moon rarity)

Kind of! It is once for weight and price and once for rarity. I could _probably_ get rid of the weight and price run though and just do that when I do the rarity. I'll look into that and see. That is a good idea.

> Each iteration writes several lines of logging code which are incredibly slow and cannot be disabled.

In 1.4.0 I did an entire revamp of the logging levels because I decided "This is dumb for the users. This is also dumb. This is helpful. This is for me." blah blah blah. Logging _CAN_ be disabled. It's a BepInEx setting. Check your BepInEx config file for the `Logging.Console` and `Logging.Disk` option. You can set that to whatever value you'd like so long as they support it. I feel that the things currently listed at the Info level are valuable for consumers, but if you think otherwise and think you'd rather see no logging then that is something I could definitely mull over.

> having a scrap pack like Dafi's scrap emporium will easily push the load times past 5-10 minutes, 

I haven't tried with scrap emporium, but I did with the moons emporium. I was getting ~25s load time at the start of a round. Somewhat painful for sure, but it seemed _kind of_ acceptable given the sheer amount of scrap and moons it had to deal with. I can throw in the scrap emporium and see what I have on my end. Of course, YMMV and speed is going to be 100% dependent upon your system. It should be mostly CPU-bound though. More on that in a sec!

> every single time you change to a new moon and land, it repeats several more iterations to write and read every single scrap item on that moon which also inflates the generation times to unbearable times.

I'm kind of shocked to hear this part. You are correct that it does loop for every single scrap item on that moon, but I really wouldn't expect this to be that noticeable. What sort of times are you seeing spent on Balanced Items when you pull the ship lever to land?

> On top of that logging cannot be disabled thus this part cannot be culled for performance, it's also insanely spammy even without any mods.

Kind of touched on this above.

> The mod also does not skip unnecessary parts (such as writing scraps and moons it already added) and iterates through the config creation as well as reading it every single time and neither does disabling any parts of the configuration make a difference.

I'm not so sure that this is the performance hit that you may be thinking it is. With the way that BepInEx config works, it is a two-way binding. It only writes a config entry (or rather, prepares one to be written) if one does not exist. If it does exist, then it reads it. So what do I mean by "prepares one to be written"? All of the config writing happens in-memory and I flush to disk after that portion of the mod has finished preparing all of the config entries. Therefore, it won't be doing dozens of write operations for dozens of config entries. It will do one write operation for all config entries at the end of that feature being prepared.

I will 100% address the part about disabling parts of the config though. That is something I had not thought of! Thanks for the idea. :)

> Disabling sell values for instance does not skip writing and reading the sell values for all moons and scraps.

I can't skip writing these config entries when the feature is disabled because you might enable it mid-game. If I skipped writing the config entries, then you enabled the feature mid-game, then it wouldn't work because no entries would exist. Furthermore, the config entries must be written during the first pass through before applying anything so that the vanilla values are correctly acknowledged. The way the game works, it stores everything in memory (yep, not super great) so when an item weight is set to XYZ, then it stays as XYZ until you set it to something else. It does not matter if you restart your session, or go to another moon. None of that resets anything! :D That actually caused me a fair amount of refactoring required for the feature toggles so that I could start storing the vanilla values.

> It makes playing with the later versions of this mod unbearably slow.

Sorry to hear that, but I'm thankful for the feedback! As mentioned above, I was waiting to see if this was an actual issue for someone, or me just having too high of expectations on myself.

> Suggestions:
> Make the mod skip parts you disabled.

This will definitely be done. Takeaway item is listed below for this.

> Allow disabling logging.

Covered this above, but that's a BepInEx setting that you can control on your end. If you meant disabling logging only for this mod, then that can be arranged! However, I really don't think that'll save anything though because logging _should_ be an asynchronous operation. Emphasis on _should_ here though because that is purely an assumption on my end based on how good logging is implemented in basically any other framework. :)

> Allow disabling hot-loading to eliminate in-lobby loading times between moons.
The hot-loading between moons should only be affecting scrap spawned on that moon. I think I touched on this a bit above, but if you could get specific metrics on how long is spent from Balanced Items on preparing the scrap on that level, I'd be grateful!

Takeaway items:
1. Don't read config entries for a specific feature if that feature toggle is currently off.

**Comment by NiranV** [comment]
Loading moons currently takes roughly 20 seconds as opposed to 2 secs without the mod. 
Loading into the lobby takes around 5 minutes for me with roughly 10 extra moons and like 300 extra scrap items.
CPU is a Ryzen 5 3600.

Writing the configs could be skipped if hot-loading is disabled, which locks in everything and writes/reads it only once on lobby load eliminating all skipped features while doing so potentially cutting the time in roughly half and eliminating the world gen loading times.

Also yea i'd like a mod-specific logging toggle as i'd like to keep all other logging intact as it contains useful information i need to look into potential issues when they happen while playing with buddies.

**Comment by Doug-Murphy** [comment]
> Loading moons currently takes roughly 20 seconds as opposed to 2 secs without the mod.

This would imply that the moon you are on is spawning _a ton_ of scrap. Vanilla without mods is longer than 2 seconds for me and the friends I play with. It even freezes with in-game VOIP not working for a few seconds for all of us. I briefly looked into it and kind of felt it was due to the map generating.

> Loading into the lobby takes around 5 minutes for me with roughly 10 extra moons and like 300 extra scrap items.

Wow that is a very, very long time. I definitely need to try the scrap mod tonight. As mentioned above, it was ~25 seconds for me with the moons emporium pack (but not scrap). I have a Ryzen 7 5800X.

> Writing the configs could be skipped if hot-loading is disabled, which locks in everything and writes/reads it only once on lobby load eliminating all skipped features while doing so potentially cutting the time in roughly half and eliminating the world gen loading times.

For which features though? And what functionality would you be sacrificing to do that? Loading the lobby seems to be your main grievance here since that's ~5 minutes. If I'm understanding you correctly, your suggestion wouldn't really help your scenario.

Can you elaborate on "eliminating all skipped features"? And what makes you think it'll be cut roughly in half?

> Also yea i'd like a mod-specific logging toggle as i'd like to keep all other logging intact as it contains useful information i need to look into potential issues when they happen while playing with buddies.

Could you list the specific log entries that you don't find value in and explain why you don't think they're valuable? I'm happy to adjust log levels. As mentioned earlier, I did a rework of that and the ones that are shown by default are ones that I thought would be useful. It should just be the times where a config entry is bound and when an override was set. This ensures that you are away of what is happening and can therefore identify when/why something isn't working.

What is your exact list of mods that you're running so that I can best try to repro this on my end. I'm still struggling to see 5 minutes for a lobby to load.

**Comment by Doug-Murphy** [comment]
@NiranV I just looked at the ConfigFile.Reload() method for BepInEx. It does far more than I originally anticipated (I should have RTFM...) but I suppose what they do does make sense. This, however, means it was absolutely terrible with how I was using it. So I just fixed that up. From the time I click "Confirm" to load my save file to the time that my eyes open up on the ship, I'm consistently seeing 8 seconds when the config file exists, and 16 seconds when the config file does not exist. That is with the mod list below.

![image](https://github.com/Doug-Murphy/LethalCompanyMods/assets/1383347/294da34e-2532-4416-912a-110212b9b6af)

I'd love to get a beta version in your hands for you to do some testing! I'll arrange that very soon (maybe within the hour) after I do some initial playtesting.

**Comment by Doug-Murphy** [comment]
@NiranV I have a beta release ready if you'd like to try it out for me!

Installation instructions can be found on [this other issue](https://github.com/Doug-Murphy/LethalCompanyMods/issues/2#issuecomment-1874235504)

https://github.com/Doug-Murphy/LethalCompanyMods/releases/tag/1.4.0-beta1

**Comment by Doug-Murphy** [comment]
I just did some testing regarding the logging. With my console logging level set to "All" I averaged ~22 seconds to start a round. With it set to "None" I averaged ~6 seconds to start a round. (Note that this is for all mods shown above, not just my mind). It seems that only the console logging impacts my times. If I have console set to "None" and disk set to "All" I still see the 6 second load time. So maybe a good takeaway here for us both is to not have console logging at all, and just rely on reading the log file on disk if you ever need to. I know I rarely use console logging, even when debugging and testing, because it's flooded with other mods and game logs. It just keeps scrolling me back to bottom.

When I set my console and disk log levels to default values, I see ~15 seconds (again, for all mods shown above). So it seems ~7 seconds additional for all the debug-level logs. If I change the log entries for "Finish adding config...." to debug, then I'm down to ~10 seconds. I agree that those should be debug level, so they have been demoted! This results in a 33% reduction in load times by fixing these two log entries.

Moving forward, I'm disabling my console logging. Not only does it snap me to bottom, get flooded with other mods/the game, but it also has a high tendency to freeze my game. :)

**Comment by Doug-Murphy** [comment]
https://github.com/Doug-Murphy/LethalCompanyMods/releases/tag/BI-1.4.1-beta2

1.4.1-beta2 is available for you! I'll release this tomorrow unless I hear of any breaking issues.

**Comment by NiranV** [comment]
Alright, i'll give it a whirl!

**Comment by NiranV** [comment]
From the quick tests i did it's a lot faster and i mean indistinguishably fast, it loads in 4-6 seconds just like without the mod. I disabled most features and did another run with all of them enabled both times no difference. From looking at the console i'd assume you are skipping all unused items now, it does still report a successful change but only for the items that are actually spawned in this current moon session, this is definitely a million times better and seems essentially completely resistant to adding more scraps and moons. Both load times into lobby and between moons has gone down to what i'd say "looks like" the same as without the mod.

Thank you very much!

**Comment by Doug-Murphy** [comment]
> From the quick tests i did it's a lot faster and i mean indistinguishably fast, it loads in 4-6 seconds just like without the mod.

Awesome! That's what I like to hear!

> From looking at the console i'd assume you are skipping all unused items now, it does still report a successful change but only for the items that are actually spawned in this current moon session

Actually I'm not skipping anything. No feature functionality was changed. :)

> Tomorrow i'll be getting some more big testing in with a bunch of friends.

Awesome! I plan to release this evening. Probably 10-12 hours from now. I'll close this issue when I release.

> Thank you very much!

Thank YOU very much!
