### ISSUE TITLE
Suggestion- Adapt Balanced items to shop item

### ISSUE THREAD

**Issue by TerpSpiceRice** [Doug-Murphy/LethalCompanyMods#30]
Im not sure this is the correct place for a suggestion like this, but figured id reach out based off the thunderstore description. I love balanced items, its perfect for creating a really custom experience in tandem with a large chunk of extra scrap mods. I have not found a solution as elegant for rebalancing the shop and would love to see your version of config generation applied to shop items if possible. Thank you for the excellent mods

**Comment by Doug-Murphy** [comment]
Thanks for the kind words! :D I'm glad I was able to make your playing experience better.

I'm not entirely sure what you mean though about applying to shop items. Can you be more specific? I have a few questions.

1. By "shop items" do you mean equipment?
2. What about shop items would you like to change?

**Comment by TerpSpiceRice** [comment]
Balanced items is honestly the perfect mod for an all in one config for items from other mods. I was hoping for something that would work similar to that, a config that lets you change prices of purchasable equipment within the terminal shop that also finds other mods and allows them to be configured. Price would be the first thing that I'd love to configure, but sales and their frequency and scale would also be neat to see if even possible.

**Comment by Doug-Murphy** [comment]
I have begun work on this feature! It appears that setting the price for equipment purchases and ship decorations is really easy. I'm still trying to figure out how to change prices for ship upgrades though. This should be a fairly simple feature to get implemented. It _does_ already account for items from other mods (I tested with buyable shotgun and buyable shotgun shells).

By sales, I assume you mean the discounts that happen randomly. That could be pretty neat to change! I haven't looked into that portion yet.

What do you mean by scale? Do you mean by how much of a discount is applied when the item is on sale?

When I get it implemented, would you be open to trying a beta release and providing feedback?

**Comment by TerpSpiceRice** [comment]
Im beyond excited, I've been working on a mod profile on R2 for some friends that helps focus on progression and end game. Rebalancing many mods has been a bit of a headache, but your config approach has been saving a lot of time. I have a lot of shop items crammed in that I'm hoping to scale better as end game content. I would love to test it with what I have set up! You also hit the nail on the head for both features.

**Comment by Doug-Murphy** [comment]
So it turns out that setting prices for ship decor is NOT easy. I was wrong earlier. But setting prices for equipment is easy and that feature is done.

I spent 3 hours tonight trying to figure out how to do it for ship upgrades and ship decor. The game doesn't seem to surface those items to you in a way that you can change the price. You can change what the price _shows_ but when you buy it, the price is the vanilla price. I have proven out a way to update that, but it's super janky and I'm not entirely sure I'll move forward with it due to the jank factor. I'll finish implementing the jank solution sometime this weekend when I can find some time and then make a decision on whether or not it will stay.

You can rest assured though that equipment item purchases will be implemented!

**Comment by TerpSpiceRice** [comment]
Its definitely not a needed feature for balance by any means, hopefully the headache still brought some interesting discoveries on the games code. Also, jank is by far one of my favorite words

**Comment by Doug-Murphy** [comment]
> Its definitely not a needed feature for balance by any means

That's good, because it might not be possible. Lol.

> hopefully the headache still brought some interesting discoveries on the games code.

Interesting is one word for it! Haha. Pretty standard discoveries from the usual "What the...." head scratchers.

I finished a really big refactor on it today and am doing playtesting of that as I type this reply. If this goes well, then I'll get back to finishing terminal price overrides. Currently the only TBD things for that is config-driven and polishing it up.

**Comment by Doug-Murphy** [comment]
@TerpSpiceRice I have a beta release of 1.6.0 ready to go for you to do some testing! It was a fairly large refactor of the existing functionality, so do let me know if you encounter any bugs or oddities with the existing features. 1.6.0 only contains the purchase price overrides for items in the shop. It does not include ship decor or ship upgrades (due to the reasons mentioned earlier).

The rest of your feature requests will take some more time and I'd like to explore that for a 1.7.0 release. I wanted to go ahead and get this feature out though since I think it's quite helpful (thanks for the idea!) and the rest of your ideas will take a bit more time.

https://github.com/Doug-Murphy/LethalCompanyMods/releases/tag/BI-1.6.0-beta1

For installation instructions, see [this other issue](https://github.com/Doug-Murphy/LethalCompanyMods/issues/2#issuecomment-1874235504). I really should just make a wiki page for this by now. Maybe I'll get a chance tonight.

**Comment by Doug-Murphy** [comment]
@TerpSpiceRice I _just_ released 1.6.0 so be on the lookout for that update on Thunderstore within the next few minutes. Thanks for the suggestions! Closing this issue.

**Comment by DeathWrench** [comment]
> @TerpSpiceRice I _just_ released 1.6.0 so be on the lookout for that update on Thunderstore within the next few minutes. Thanks for the suggestions! Closing this issue.

If you still need help with making decorations free:
https://github.com/7PH/free-ship-decorations-lethal-company-mod

**Comment by TerpSpiceRice** [comment]
> @TerpSpiceRice I _just_ released 1.6.0 so be on the lookout for that update on Thunderstore within the next few minutes. Thanks for the suggestions! Closing this issue.

Sweet, I cant wait to try it out. Im sorry I couldnt test it in the earlier phase, life swept me up for a minute. Thank you for the addition!
