### ISSUE TITLE
Lag spike / freeze when items "drop" from the dropship

### ISSUE THREAD

**Issue by Fl4sHNoX** [Doug-Murphy/LethalCompanyMods#34]
When looking at the debug console when interacting with the dropship for it to drop the items, it seems to correlate with a huge lag/freeze of the game for a brief instant.

I assume it may be related to some kind of dynamic attribution of weight/sell price to items that just spawn?

cf. screencapture

(N.B.: It doesn't seem to come from Diversity as I encounter the same issue without it installed/enabled)

https://github.com/Doug-Murphy/LethalCompanyMods/assets/3759901/139feb4f-28dc-4ee5-8a72-f310cf7d9aac

**Comment by Doug-Murphy** [comment]
This issue was discussed at length, and had a few iterations of testing, via the LC Modding Discord. Here's the summary of that discussion:

@Fl4sHNoX is using a modpack with 274 mods in it. A few dozen of these are disabled, but that still results in 200+ mods being in the modpack. The game is noticeably laggy when launching the game, when loading the game session, and even when simply moving around the map. I think this winds up as being the scenario of asking too much of the game. It simply cannot handle all of this logic in the same thread, and there could be dozens of other mods in this pack also asking for attention with grabbable object spawns. The logs don't necessarily indicate that, but logging is 100% dependent upon the mod to do.

The only theory I could come up with was the hot-reloading nature of the config file for each grabbable object being spawned. This functionality allows the user to change the item's weight and have it reflect in the game for newly-spawned items. The issue with this is that it has to do a `.Reload()` on the config file, which is quite large for this modpack. The BepInEx config handling system isn't exactly performant with reloading from the config file, and has been known to cause some issues for Balanced Items in the past. However, those were addressed and it is now (I believe) in its best possible state. Even with removing the hot-reload functionality, the lag spike was present as shown in this video thus leading it to be not a hot-reload issue. That is the only reasonable performance issue from this code in this scenario as the rest is all operating in-memory which will pretty much always be instantaneous.

Lastly, disabling Balanced Items from this modpack did not have a noteworthy impact on the lag spike when the dropship opens, which kind of rules out Balanced Items from being a big offender, if an offender at all, of this lag spike for the dropship.
